@url=http://localhost:3000/events

### CRIAR
POST {{url}}
Content-Type: application/json

{
    "person": 1,
    "type": "security",
    "associatedDevice": 1,
    "timestamp": "2024-05-12",
    "additionalDetails": "teste teste"
}


### GET ALL
GET {{url}}

### Get by ID
GET {{url}}/664bcf0d707d6396f1ccfbce