@url=http://localhost:5000/users
@authUrl=http://localhost:5000/login

### CRIAR
POST {{url}}
Content-Type: application/json

{
    "name": "Juca",
    "email": "juca@gmail.com",
    "password": "12346764575",
    "birth": "2000-01-01"
}

### LOGIN (para obter o token JWT)
POST {{authUrl}}
Content-Type: application/json

{
    "email": "juca@gmail.com",
    "password": "1234"
}

### Salve o token retornado aqui após fazer login
@token=YOUR_JWT_TOKEN_HERE

### GET ALL (usando token JWT)
GET {{url}}
# Authorization: Bearer {{token}}

### GET by ID (usando token JWT)
GET {{url}}/664bd8875380180edfb8c0e9
Authorization: Bearer {{token}}

### PUT (usando token JWT)
PUT {{url}}/662b902e5495ba0f117013c0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Ronaldo Fenomeno"
}

### DELETE by ID (usando token JWT)
DELETE {{url}}/665fba26ad3598830faa8ce0
# Authorization: Bearer {{token}}
